services:
  {{ service_name }}:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - {{ repo_root }}:{{ working_dir }}:ro
      - ./{{ service_name }}.conf:/etc/nginx/conf.d/default.conf:ro
{% if services["php-fpm"] and services["php-fpm"].params["isolated_dirs"] %}
{% for dir in services["php-fpm"].params["isolated_dirs"] %}
      - {{ project_name }}-{{ services["php-fpm"].name }}{{ services["php-fpm"].params["working_dir"] | replace("/", "-") | replace("_", "-") }}-{{ dir | replace("/", "-") | replace("_", "-") }}:{{ working_dir }}/{{ dir }}:ro
{% endfor %}
{% endif %}
{% if services["php-fpm"] %}
    depends_on:
      {{ services["php-fpm"].name }}:
        condition: service_started
{% endif %}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q -O /dev/null http://127.0.0.1:80/ >/dev/null 2>&1; code=$?; [ \"$code\" -eq 0 ] || [ \"$code\" -eq 8 ]",
        ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
