#!/usr/bin/env python3
"""Exercise the entrypoints generated by the pack's workspace Dockerfiles."""

from __future__ import annotations

import json
import os
import socket
import stat
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

PACK_ROOT = Path(__file__).resolve().parents[1] / "pack"
DOCKERFILES = {
    "workspace-rust-bun": PACK_ROOT / "workspace-rust-bun" / "Dockerfile",
    "php-fpm": PACK_ROOT / "php-fpm" / "Dockerfile",
}


class CheckFailure(RuntimeError):
    pass


def require(condition: bool, message: str) -> None:
    if not condition:
        raise CheckFailure(message)


def generated_entrypoint(dockerfile: Path, fixture: Path) -> Path:
    lines = dockerfile.read_text(encoding="utf-8").splitlines(keepends=True)
    try:
        marker = next(index for index, line in enumerate(lines) if "SSH agent socket bridge" in line)
        start = next(index for index in range(marker + 1, len(lines)) if lines[index].startswith("RUN set -eux; " + chr(92)))
        end = next(
            index
            for index in range(start + 1, len(lines))
            if "chmod 0755 /usr/local/bin/effigy-entrypoint" in lines[index]
        )
    except StopIteration as error:
        raise CheckFailure(f"{dockerfile}: could not locate the entrypoint generation block") from error

    generated = fixture / "generated" / "effigy-entrypoint"
    generated.parent.mkdir(parents=True)
    block = "".join(lines[start + 1 : end + 1]).replace("/usr/local/bin/effigy-entrypoint", str(generated))
    generation_script = fixture / "generate-entrypoint.sh"
    generation_script.write_text(block, encoding="utf-8")
    result = subprocess.run(["bash", "-e", "-u", str(generation_script)], cwd=fixture, text=True, capture_output=True)
    require(result.returncode == 0, f"{dockerfile}: generation failed: {result.stderr.strip()}")
    require(generated.is_file(), f"{dockerfile}: generation block did not create an entrypoint")
    return generated


def write_executable(path: Path, contents: str) -> None:
    path.write_text(contents, encoding="utf-8")
    path.chmod(0o755)


def fixture_tools(root: Path) -> tuple[Path, Path]:
    fakebin = root / "fakebin"
    fakebin.mkdir()

    write_executable(
        fakebin / "id",
        """#!/bin/bash
case "${1-}:${2-}:$#" in
  -u:dev:2) echo 1000 ;;
  -g:dev:2) echo 1000 ;;
  -gn:dev:2) echo dev ;;
  -u::1) echo "${FAKE_ENTRYPOINT_UID:-$(/usr/bin/id -u)}" ;;
  -g::1) echo "${FAKE_ENTRYPOINT_GID:-$(/usr/bin/id -g)}" ;;
  *) exec /usr/bin/id "$@" ;;
esac
""",
    )
    write_executable(
        fakebin / "chown",
        """#!/bin/bash
printf '%s\\n' "$*" >>"${FAKE_CHOWN_LOG:?}"
""",
    )
    write_executable(
        fakebin / "update-ca-certificates",
        """#!/bin/bash
printf 'invoked\\n' >>"${FAKE_UPDATE_CA_LOG:?}"
if [ "${FAKE_UPDATE_CA_EXIT:-0}" != 0 ]; then
  printf 'fake update-ca-certificates failing on request\\n' >&2
  exit "$FAKE_UPDATE_CA_EXIT"
fi
printf 'fake update-ca-certificates succeeded\\n'
""",
    )
    write_executable(
        fakebin / "socat",
        """#!/bin/bash
printf '%s\\n' "$@" >>"${FAKE_SOCAT_LOG:?}"
for arg in "$@"; do
  case "$arg" in
    UNIX-LISTEN:*)
      listen_path="${arg#UNIX-LISTEN:}"
      listen_path="${listen_path%%,*}"
      python3 - "$listen_path" <<'PY'
import os, socket, sys
path = sys.argv[1]
server = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
server.bind(path)
os.chmod(path, 0o600)
server.close()
PY
      ;;
  esac
done
""",
    )
    write_executable(fakebin / "docker-php-entrypoint", "#!/bin/bash\nexec \"$@\"\n")

    probe = root / "requested-command.py"
    probe.write_text(
        """import json, os, sys
from pathlib import Path
Path(os.environ['ENTRYPOINT_MARKER']).write_text(json.dumps(sys.argv[1:]), encoding='utf-8')
raise SystemExit(int(os.environ.get('PROBE_EXIT', '0')))
""",
        encoding="utf-8",
    )
    return fakebin, probe


def prepare_case(
    *,
    fixture: Path,
    generated: Path,
    dockerfile: Path,
    name: str,
    fakebin: Path,
    probe: Path,
    simulated_uid: int | None = None,
    log_mode: str = "writable",
    socket_present: bool = False,
    ca_present: bool = False,
    update_ca_exit: int = 0,
    probe_exit: int = 0,
) -> dict[str, Any]:
    case = fixture / name
    case.mkdir()
    paths = {
        "host_sock": case / "run" / "host-services" / "ssh-auth.sock",
        "bridge_sock": case / "tmp" / "effigy-ssh-auth.sock",
        "log": case / "state" / "effigy-ssh-bridge.log",
        "mkcert_ca": case / "ca" / "effigy-mkcert.crt",
    }
    for directory in {path.parent for path in paths.values()}:
        directory.mkdir(parents=True, exist_ok=True)
    if socket_present:
        server = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        server.bind(str(paths["host_sock"]))
        server.close()
    if ca_present:
        paths["mkcert_ca"].write_text("fixture CA\n", encoding="utf-8")

    php_secrets = case / "run" / "effigy" / "secrets"
    php_bootstrap = case / "usr-local-share" / "container-secrets-bootstrap.php"
    php_msmtprc = case / "etc" / "msmtprc"
    php_bootstrap.parent.mkdir(parents=True)
    php_bootstrap.write_text("<?php return;\n", encoding="utf-8")
    php_secrets.parent.mkdir(parents=True)
    php_msmtprc.parent.mkdir(parents=True)

    entrypoint = case / "entrypoint"
    replacements = {
        "host_sock=/run/host-services/ssh-auth.sock": f"host_sock='{paths['host_sock']}'",
        "bridge_sock=/tmp/effigy-ssh-auth.sock": f"bridge_sock='{paths['bridge_sock']}'",
        "log=/var/log/effigy-ssh-bridge.log": f"log='{paths['log']}'",
        "mkcert_ca=/usr/local/share/ca-certificates/effigy-mkcert.crt": f"mkcert_ca='{paths['mkcert_ca']}'",
        "/run/effigy/secrets": str(php_secrets),
        "/usr/local/share/effigy/container-secrets-bootstrap.php": str(php_bootstrap),
        "/etc/msmtprc": str(php_msmtprc),
    }
    source = generated.read_text(encoding="utf-8")
    for old, new in replacements.items():
        source = source.replace(old, new)
    entrypoint.write_text(source, encoding="utf-8")
    entrypoint.chmod(0o755)

    if log_mode == "directory-unwritable":
        paths["log"].parent.chmod(0o555)
    elif log_mode == "file-unwritable":
        paths["log"].write_text("prior root log\n", encoding="utf-8")
        paths["log"].chmod(0o444)
    else:
        paths["log"].touch()

    marker = case / "argv.json"
    update_log = case / "update-ca.log"
    socat_log = case / "socat.log"
    chown_log = case / "chown.log"
    env = os.environ.copy()
    env.update(
        {
            "PATH": f"{fakebin}:{os.environ.get('PATH', '')}",
            "ENTRYPOINT_MARKER": str(marker),
            "FAKE_UPDATE_CA_LOG": str(update_log),
            "FAKE_SOCAT_LOG": str(socat_log),
            "FAKE_CHOWN_LOG": str(chown_log),
            "FAKE_UPDATE_CA_EXIT": str(update_ca_exit),
            "PROBE_EXIT": str(probe_exit),
        }
    )
    if simulated_uid is None:
        env.pop("FAKE_ENTRYPOINT_UID", None)
    else:
        env["FAKE_ENTRYPOINT_UID"] = str(simulated_uid)
    if dockerfile == DOCKERFILES["php-fpm"]:
        command: list[str] = ["docker-php-entrypoint", "python3", str(probe), "--alpha", "beta two", "gamma"]
    else:
        command = ["python3", str(probe), "--alpha", "beta two", "gamma"]

    result = subprocess.run(
        ["bash", str(entrypoint), *command], cwd=case, env=env, text=True, capture_output=True, timeout=15
    )
    return {
        "case": case,
        "paths": paths,
        "entrypoint": entrypoint,
        "marker": marker,
        "result": result,
        "update_log": update_log,
        "socat_log": socat_log,
        "simulated_uid": simulated_uid,
        "probe_exit": probe_exit,
        "log_mode": log_mode,
    }


def assert_command(result: dict[str, Any], label: str) -> None:
    process = result["result"]
    require(process.returncode == result["probe_exit"], f"{label}: expected command exit {result['probe_exit']}, got {process.returncode}; stderr={process.stderr!r}")
    require(result["marker"].is_file(), f"{label}: requested command did not run")
    argv = json.loads(result["marker"].read_text(encoding="utf-8"))
    require(argv == ["--alpha", "beta two", "gamma"], f"{label}: argv changed: {argv!r}")


def run_dockerfile_check(name: str, dockerfile: Path, fixture: Path) -> int:
    generated = generated_entrypoint(dockerfile, fixture)
    fakebin, probe = fixture_tools(fixture)
    generated_source = generated.read_text(encoding="utf-8")
    require('exec "$@"' in generated_source, f"{name}: entrypoint no longer execs the requested command")
    require("mode=0600" in generated_source, f"{name}: bridge socket mode 0600 protection is missing")
    require("user=$dev_uid,group=$dev_gid,mode=0600" in generated_source, f"{name}: root bridge ownership/mode protection is missing")

    passes = 0
    base = prepare_case(
        fixture=fixture,
        generated=generated,
        dockerfile=dockerfile,
        name="argv",
        fakebin=fakebin,
        probe=probe,
        simulated_uid=0,
        probe_exit=7,
    )
    assert_command(base, f"{name} root-mode argv/exit")
    require("dev uid=1000 gid=1000" in base["paths"]["log"].read_text(), f"{name}: root branch omitted dev identity diagnostics")
    passes += 1

    bridge = prepare_case(
        fixture=fixture,
        generated=generated,
        dockerfile=dockerfile,
        name="bridge",
        fakebin=fakebin,
        probe=probe,
        simulated_uid=0,
        socket_present=True,
        ca_present=True,
    )
    assert_command(bridge, f"{name} root-mode forwarding/trust")
    socat_args = bridge["socat_log"].read_text(encoding="utf-8").splitlines()
    require(any("user=1000,group=1000,mode=0600" in arg for arg in socat_args), f"{name}: root bridge did not retain dev ownership and mode 0600")
    require(stat.S_IMODE(bridge["paths"]["bridge_sock"].stat().st_mode) == 0o600, f"{name}: bridge socket mode was not 0600")
    require("mkcert root CA installed into system trust store" in bridge["paths"]["log"].read_text(), f"{name}: successful trust installation was not logged")
    require(bridge["update_log"].is_file(), f"{name}: update-ca-certificates was not invoked")
    passes += 1

    trust_failure = prepare_case(
        fixture=fixture,
        generated=generated,
        dockerfile=dockerfile,
        name="trust",
        fakebin=fakebin,
        probe=probe,
        simulated_uid=0,
        log_mode="directory-unwritable",
        ca_present=True,
        update_ca_exit=23,
    )
    assert_command(trust_failure, f"{name} failed trust setup")
    diagnostic = trust_failure["result"].stderr
    require("fake update-ca-certificates failing on request" in diagnostic, f"{name}: failed trust command output was not visible on stderr")
    require("WARNING update-ca-certificates failed; root trust was not updated" in diagnostic, f"{name}: trust failure diagnostic was not visible on stderr")
    require("mkcert root CA installed into system trust store" not in diagnostic, f"{name}: failed trust setup was reported as successful")
    passes += 1

    for suffix, mode in (("log-directory", "directory-unwritable"), ("log-file", "file-unwritable")):
        nonroot = prepare_case(
            fixture=fixture,
            generated=generated,
            dockerfile=dockerfile,
            name="logdir" if mode == "directory-unwritable" else "logfile",
            fakebin=fakebin,
            probe=probe,
            log_mode=mode,
            ca_present=mode == "file-unwritable",
        )
        require(os.geteuid() != 0, "non-root entrypoint proof requires this worker to run as a non-root host user")
        assert_command(nonroot, f"{name} non-root {suffix}")
        stderr = nonroot["result"].stderr
        require("WARNING host_sock missing" in stderr, f"{name}: missing host forwarding diagnostic is not on stderr")
        require("bridge_sock created" not in stderr + nonroot["result"].stdout, f"{name}: claimed bridge creation without a host socket")
        require("WARNING bridge log unavailable" in stderr, f"{name}: unwritable log diagnostic is not on stderr")
        if mode == "file-unwritable":
            require("WARNING non-root startup cannot install the mkcert root CA; system trust was not updated" in stderr, f"{name}: non-root trust limitation was not reported")
            require(not nonroot["update_log"].exists(), f"{name}: tried to install system trust as non-root")
            require("mkcert root CA installed into system trust store" not in stderr, f"{name}: claimed root trust was installed as non-root")
        if name == "php-fpm":
            require("cannot initialize root-owned PHP secrets or msmtp configuration" in stderr, f"{name}: non-root setup limitation was not reported")
        if mode == "directory-unwritable":
            require(not nonroot["paths"]["log"].exists(), f"{name}: created a log inside the unwritable directory")
        else:
            require(nonroot["paths"]["log"].read_text(encoding="utf-8") == "prior root log\n", f"{name}: changed an existing unwritable log")
        passes += 1

    return passes


def main() -> int:
    require(os.geteuid() != 0, "run this proof as a non-root host user; it uses only a private temporary fixture")
    total = 0
    with tempfile.TemporaryDirectory(prefix="ecp-", dir="/tmp") as temp:
        fixture_root = Path(temp)
        for name, dockerfile in DOCKERFILES.items():
            total += run_dockerfile_check(name, dockerfile, fixture_root / name)
    print(f"Summary: {total} passed, 0 skipped, 0 failed")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (CheckFailure, OSError, subprocess.SubprocessError) as error:
        print(f"[error] {error}", file=sys.stderr)
        raise SystemExit(1)
